[env:esp32s3_compagnon]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Board overrides
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = partitions/compagnon_16mb.csv

; MCU settings
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_FREERTOS_UNICORE=0
    ; LVGL
    -DLV_CONF_INCLUDE_SIMPLE
    ; Timezone
    -DTIMEZONE_OFFSET=3600

; Libraries
lib_deps =
    lvgl/lvgl@^8.3.0
    bblanchon/ArduinoJson@^7.0.0
    madhephaestus/ESP32AnalogRead@^0.2.1

; Serial monitor
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, colorize

; Upload
upload_speed = 921600
