[env:compagnon_v2]
platform              = espressif32 @ 6.11.0
board                 = waveshare_esp32s3_touch_amoled_216
framework             = arduino

board_build.flash_mode         = qio
board_build.psram_type         = opi
board_build.arduino.memory_type = qio_opi

monitor_speed = 115200
upload_speed  = 921600

board_build.partitions = partitions.csv

lib_deps =
    moononournation/Arduino_GFX_Library @ ^1.4.9
    lewisxhe/SensorLib @ ^0.3.0
    lewisxhe/XPowersLib @ ^0.2.6
    h2zero/NimBLE-Arduino @ ^1.4.2
    bblanchon/ArduinoJson @ ^7.3.0
    lvgl/lvgl @ ^9.2.2
    luc-github/ESP32-audioI2S @ ^2.1.1

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=0
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_CONF_PATH="${PROJECT_DIR}/firmware/src/config/lv_conf.h"
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_FREERTOS_UNICORE=0
    -DLV_MEM_SIZE=524288
    -DCONFIG_ESP32S3_DEFAULT_CPU_FREQ_240=1
    -mfix-esp32-psram-cache-issue
